application: geomancer-api
version: beta
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

handlers:

- url: /api/georef.*
  script: geomancer.api.handler

- url: /oauth/.*
  script: geomancer.oauth.handler
  login: admin