application: geomancer-api
version: beta
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

handlers:

- url: /api.*
  script: geomancer.api.handler
  
- url: /admin/.*
  script: admin.handler
  login: admin